name: Pandoc Fun
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set-up Pandoc
        uses: ${{ github.workspace }}/.github/workflows/setup-pandoc@v2
      - name: Set permissions
        run: cd ${{ github.workspace }}
            chmod 740 src/generate.sh
            chmod 740 src/generate.sh
      - name: Generate files
        run: ./src/generate.sh
      - name: Build Readme
        run: ./src/build.sh